### ISSUE TITLE
what do with missing local files

### ISSUE THREAD

**Issue by iamstarkov** [iamstarkov/eslint-plugin-lost-unicorns#19]
i dunno, lets discuss

**Comment by iamstarkov** [comment]
lets exclude them from the graph output, 'cause what we need is extra files, not missing ones. what do you think?
/cc @kinday @yakhinvadim

**Comment by kinday** [comment]
What rules will the plugin have? Why throw away extra files if we can use them in other rules?

We can have `no-unused` for files that never imported and `no-missing` for imports that don’t resolve.

**Comment by iamstarkov** [comment]
there is already `require-path-exists` plugin which implemented `no-missing` feature

**Comment by yakhinvadim** [comment]
missing local files are also covered in [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) plugin  in rule [no-unresolved](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md), so, i agree on excluding them. We can add this link in readme, in case someone is looking for this feature.

**Comment by iamstarkov** [comment]
though in process of abstracting graph into separate package i agree that missing files should not be excluded from output

**Comment by kinday** [comment]
Okay, if there are two plugins covering ours, what are we doing here, huh?

**Comment by iamstarkov** [comment]
there are no plugins to cover abandoned files. am i missing smth?

**Comment by kinday** [comment]
Yep, my bad.

Anyway, it is cheap for us to implement `no-missing` rule, so why not to compete?

**Comment by iamstarkov** [comment]
thats good idea, lets do it after abandoned rule
